const { Octokit } = require('octokit');

// Initialize Octokit
const getOctokit = () => {
  return new Octokit({ auth: process.env.GITHUB_TOKEN });
};

/**
 * Format the severity as an emoji badge
 */
const getSeverityBadge = (severity) => {
  switch (severity) {
    case 'Critical': return '🔴 **CRITICAL**';
    case 'Warning': return '🟡 **WARNING**';
    case 'Suggestion': return '🟢 **SUGGESTION**';
    default: return '⚪ **INFO**';
  }
};

/**
 * Format issue type with icon
 */
const getIssueIcon = (issueType) => {
  switch (issueType) {
    case 'Bug': return '🐛';
    case 'Security': return '🔐';
    case 'Performance': return '⚡';
    case 'Style': return '🎨';
    case 'Best Practice': return '📘';
    default: return '📋';
  }
};

/**
 * Get the quality score visual bar
 */
const getScoreBar = (score) => {
  const filled = Math.round(score / 10);
  const empty = 10 - filled;
  const bar = '█'.repeat(filled) + '░'.repeat(empty);

  let color = '🟢';
  if (score < 50) color = '🔴';
  else if (score < 75) color = '🟡';

  return `${color} \`${bar}\` **${score}/100**`;
};

/**
 * Build the full review comment in GitHub-flavored Markdown
 */
const formatReviewComment = (analysisResult) => {
  const { totalIssues, codeQualityScore, summary, issues } = analysisResult;

  let comment = `## 🛡️ GitGuard AI — Code Review Report\n\n`;
  comment += `> Automated analysis powered by AI\n\n`;

  // Quality Score
  comment += `### 📊 Code Quality Score\n`;
  comment += `${getScoreBar(codeQualityScore)}\n\n`;

  // Summary
  comment += `### 📝 Summary\n`;
  comment += `${summary}\n\n`;

  // Stats
  if (totalIssues === 0) {
    comment += `### ✅ No Issues Found\n`;
    comment += `Great work! This code looks clean and well-written. 🎉\n\n`;
  } else {
    // Count by severity
    const criticals = issues.filter(i => i.severity === 'Critical').length;
    const warnings = issues.filter(i => i.severity === 'Warning').length;
    const suggestions = issues.filter(i => i.severity === 'Suggestion').length;

    comment += `### 📈 Issues Overview\n`;
    comment += `| Severity | Count |\n`;
    comment += `|----------|-------|\n`;
    if (criticals > 0) comment += `| 🔴 Critical | ${criticals} |\n`;
    if (warnings > 0) comment += `| 🟡 Warning | ${warnings} |\n`;
    if (suggestions > 0) comment += `| 🟢 Suggestion | ${suggestions} |\n`;
    comment += `| **Total** | **${totalIssues}** |\n\n`;

    // Detailed Issues
    comment += `---\n\n`;
    comment += `### 🔍 Detailed Findings\n\n`;

    issues.forEach((issue, index) => {
      comment += `#### ${index + 1}. ${getIssueIcon(issue.issueType)} ${issue.issueType} — ${getSeverityBadge(issue.severity)}\n\n`;

      if (issue.fileName) {
        comment += `📁 **File:** \`${issue.fileName}\`\n\n`;
      }

      comment += `**Issue:** ${issue.description}\n\n`;

      if (issue.suggestedFix) {
        comment += `**Suggested Fix:**\n`;
        comment += `\`\`\`\n${issue.suggestedFix}\n\`\`\`\n\n`;
      }

      comment += `---\n\n`;
    });
  }

  // Footer
  comment += `\n<sub>🤖 Review generated by **GitGuard AI** • Automated Pull Request Sentinel</sub>\n`;

  return comment;
};

/**
 * Post the review comment to the GitHub Pull Request
 */
const postReviewComment = async (owner, repo, prNumber, analysisResult) => {
  const token = process.env.GITHUB_TOKEN;

  if (!token || token === 'your_github_personal_access_token_here') {
    console.log('⚠️ GitHub token not configured — skipping comment posting');
    console.log('📝 Comment that would have been posted:');
    console.log(formatReviewComment(analysisResult).substring(0, 500) + '...');
    return;
  }

  const octokit = getOctokit();
  const comment = formatReviewComment(analysisResult);

  try {
    await octokit.rest.issues.createComment({
      owner,
      repo,
      issue_number: prNumber,
      body: comment
    });

    console.log(`✅ Review comment posted to ${owner}/${repo}#${prNumber}`);
  } catch (error) {
    console.error(`❌ Failed to post comment: ${error.message}`);
    throw error;
  }
};

module.exports = { postReviewComment, formatReviewComment };
